[project]
name = "newbili2text"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "moviepy[editor]>=2.1.2",
    "pydub>=0.25.1",
    "requests>=2.32.3",
    "ttkbootstrap>=1.12.0",
    "whisper>=1.1.10",
]
